### ISSUE TITLE
the connection plugin 'sshjail' was not found

### ISSUE THREAD

**Issue by htgoebel** [austinhyde/ansible-sshjail#10]
When using the `dev_ansible_v2` branch with ansible 2.0.0.2, I get the error:

> ERROR! the connection plugin 'sshjail' was not found

The file itself is found and compiled.

Using your patched version of ansible is not an option for me.

**Comment by austinhyde** [comment]
Hi, yes, that's the reason I submitted a patch to Ansible.

I'll tweak things so that it can work without the patch.
