### ISSUE TITLE
become password per host

### ISSUE THREAD

**Issue by Sec42** [austinhyde/ansible-sshjail#18]
I have ansible_become_pass saved in an ansible vault under
host_vars/freebsdhost
which makes normal ansible playbooks run fine bs. that host.

If I run it against a jail, ansible thinks the hostname is jail@hostname, and thus looks for a
host_vars/jail@freebshost file.

I am currently solving that by creating a symlink per jail in the host_vars/ directory, but this seems very inefficient.

Is there a better way to do this? Can ansible be convinced to read the settings for the base host?

**Comment by BigJ64** [comment]
The way I've handled things like that in the past is create a group in the inventory that has the title **[freebsdhost]** and then put all the jails in that group along with the jailhost.  Once that's done you can create a **group_vars/freebsdhost** directory and place the vaulted ansible_become_pass there. It should respect it from that location based on what I see in the variable precedence ansible lays out for 2.x: http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

**Comment by Sec42** [comment]
You're right. I guess I was too fixated on "it's the same host" to see that solution. I have changed it to group_vars and it works fine. Thanks.
