### ISSUE TITLE
Fix for Ansible 2.5

### ISSUE THREAD

**Issue by basarevych** [austinhyde/ansible-sshjail#19]
Just FYI Ansible 2.5 will die without DOCUMENTATION string from the original ssh plugin. I think it validates the options from the string now.

**Comment by domodwyer** [comment]
Is there a workaround for this? 

I'll happily open a PR, I just don't know what `DOCUMENTATION string` @basarevych is referring to.

**Comment by hc-bondis** [comment]
@basarevych @domodwyer  Its the Modue / Plugin documetation used by ansible. Its located in the ssh connection plugin ansible/plugins/connection/ssh.py  ans starts with

DOCUMENTATION = '''
    connection: ssh
    short_description: connect via ssh client binary
    description:
...

Ansible 2.5 is more strict about documentation and refuses to work if missing or incorrect.

**Comment by austinhyde** [comment]
This should be resolved now that #20 has been merged. Thanks @madpilot78!
