### ISSUE TITLE
Upload file works

### ISSUE THREAD

**Issue by kototama** [austinhyde/ansible-sshjail#21]
You wrote "Fetching files hasn't been tested yet. It may not work.". Just wanted to say I tried the template plugin and it works! It's only needed to change the ansible `remote_tmp` variable to something like `remote_tmp=/tmp/.ansible`

Cool software, thank you, very very helpful!

**Comment by dch** [comment]
@kototama do you want to send a PR for the README? would be a great easy commit.

**Comment by austinhyde** [comment]
@kototama just to clarify, do you mean that copying files _to_ the target host or _from_ the target host works? Usually `template` copies from your local to the remote host.

**Comment by kototama** [comment]
Copying from local to remote works. Was it expected? I may have misunderstood the documentation.

**Comment by kototama** [comment]
I will be short in time to do that.

**Comment by austinhyde** [comment]
Copying a file from local to remote - uploading - is known to work.

The bit in the README is specifically about copying files from remote to local - downloading. For example, using the `fetch` module. I just tried it, and was not successful:
```yaml
- name: fetch file
  fetch:
    src: /etc/resolv.conf
    dest: test.resolv.conf
    flat: true
```
```
    bootstrap: TASK [redis : fetch file] ******************************************************
    bootstrap: fatal: [redis1]: FAILED! => {"msg": "Unable to create local directories(/vagrant/vagrant/test.resolv.conf/redis1/etc): [Errno 13] Permission denied: b'/vagrant/vagrant/test.resolv.conf'"}
    bootstrap: fatal: [redis0]: FAILED! => {"msg": "Unable to create local directories(/vagrant/vagrant/test.resolv.conf/redis0/etc): [Errno 13] Permission denied: b'/vagrant/vagrant/test.resolv.conf'"}
```

I'm not sure if this is related to my vagrant setup or a problem with the plugin. I'll try to get it working, and if not successful, I'll update the README and open a tracking issue

**Comment by austinhyde** [comment]
Update: it was indeed a problem with vagrant. I've verified that file downloading works as expected, and removed the note in the readme accordingly.
