### ISSUE TITLE
Quotes & strip: can't open file <temporary remote script.py>

### ISSUE THREAD

**Issue by fdutheil** [austinhyde/ansible-sshjail#24]
Hello, quotes nightmare seems to be back (#12). So like before I deployed my very best dev skills by calling print() ^^.
`cmd strip` show the returned value of `_strip_sudo()` and `cmd exec` the value in `exec_command()` right after the composition of the final command (if I get this corectly: `cmd = ' '.join([executable, '-c', pipes.quote(cmd)])`)
I use python 2.7.14 and ansible v2.5.6 and v2.6.1 give the same output:
```
$ ansible jail -i inventory -m ping -v

cmd exec: /bin/sh -c '/bin/sh -c '"'"'echo ~igor'"'"''
cmd exec: /bin/sh -c '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~igor/.ansible/tmp/ansible-tmp-1533806098.24-152749480273424 `" && echo ansible-tmp-1533806098.24-152749480273424="` echo ~igor/.ansible/tmp/ansible-tmp-1533806098.24-152749480273424 `" )'"'"''
cmd exec: /bin/sh -c '/bin/sh -c '"'"'chmod u+x '"'"'"'"'"'"'"'"'~igor/.ansible/tmp/ansible-tmp-1533806098.24-152749480273424/'"'"'"'"'"'"'"'"' '"'"'"'"'"'"'"'"'~igor/.ansible/tmp/ansible-tmp-1533806098.24-152749480273424/ping.py'"'"'"'"'"'"'"'"''"'"''
cmd strip: /usr/local/bin/python '"'"'"'"'"'"'"'"'~igor/.ansible/tmp/ansible-tmp-1533806098.24-152749480273424/ping.py'"'"'"'"'"'"'"'"'
cmd exec: /bin/sh -c '/usr/local/bin/python '"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'~igor/.ansible/tmp/ansible-tmp-1533806098.24-152749480273424/ping.py'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"''
cmd exec: /bin/sh -c '/bin/sh -c '"'"'rm -f -r '"'"'"'"'"'"'"'"'~igor/.ansible/tmp/ansible-tmp-1533806098.24-152749480273424/'"'"'"'"'"'"'"'"' > /dev/null 2>&1'"'"''

jail | FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n",
    "module_stdout": "/usr/local/bin/python: can't open file '\"'\"'\"'~igor/.ansible/tmp/ansible-tmp-1533806098.24-152749480273424/ping.py'\"'\"'\"': [Errno 2] No such file or directory\r\n",
    "msg": "MODULE FAILURE",
    "rc": 2
}
```
Igor is my become_user here and sudo is enabled. It seems to confirm than a lot of uninvited double-quotes have join the party around the name of the temporary python script on remote hosts.

What do you think?

**Comment by dch** [comment]
@fdutheil do you still get this on ansible 2.7.* as I don't see it. I have seen this issue come and go as upstream also tries to find exactly the right number and type of nested quotes. It's almost as if tunneling python source code to the server isn't really the right approach to doing sysadmin work *shrugs*

**Comment by fdutheil** [comment]
Hi @dch,
Thank you for the update.

I updated to ansible 2.7.5, got latest GIT version of sshjail, and I still get this:
```
$ ansible jail -i inventory -m ping

jail | FAILED! => {
    "changed": false,
    "module_stderr": "Connection to 127.0.0.1 closed.\r\n",
    "module_stdout": "/usr/local/bin/python: can't open file '\"'\"'\"'~igor/.ansible/tmp/ansible-tmp-1550596203.7999833-240778608663086/AnsiballZ_ping.py'\"'\"'\"': [Errno 2] No such file or directory\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 2
}

```

**Comment by fdutheil** [comment]
Hi,
I'm still the only one affected by this? Someone else is using "become" and sudo in the jails' host and in jails? (sorry for closing/reopening mess, I missclicked ^^)

**Comment by austinhyde** [comment]
Hi @fdutheil sorry that I'm coming around super late on this... I don't suppose you can speak to whether this is still an issue for you? Especially on more recent ansible?

**Comment by fdutheil** [comment]
> Hi @fdutheil sorry that I'm coming around super late on this... I don't suppose you can speak to whether this is still an issue for you? Especially on more recent ansible?

Hi Austin!
No worry, that's how "life" works ^^
Indeed I had to move along and reorganize my little jails infrastructure to be ssh-enabled again. For now, I'll close this issue and refer to it later if I have time to give sshjail a go again ;)

**Comment by austinhyde** [comment]
I'm sorry to hear that you never got it working.

When I was testing some changes in another PR the other week, I didn't notice anything like this, so I wonder if it was something specific to your setup?

There's a small chance that PR (now accepted and on master) fixed this issue because it changed the way we build file copy commands, but given the absurdness of the way Ansible generates commands and quotes things, I doubt it's fixed :(

Best of luck with your setup, and I'm sorry I wasn't able to make this work for you when you needed it

**Comment by wombelix** [comment]
Not to reopen the issue, more for documentation purpose in case someone else has the same problem.

```

<jailhost.example.com> (2, b'/usr/local/bin/python3.8: can\'t open file \'"\'"\'"\'~ansible/.ansible/tmp/ansible-tmp-1648330350.7033346-13083-29065725208230/AnsiballZ_setup.py\'"\'"\'"\': [Errno 2] No such file or directory\r\n', b'Shared connection to jailhost.example.com closed.\r\n')
<jailhost.example.com> Failed to connect to the host via ssh: Shared connection to jailhost.example.com closed.
<static@jailhost.example.com> ESTABLISH SSH CONNECTION FOR USER: ansible
<jailhost.example.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ansible"' -o ConnectTimeout=10 -o ControlPath=/home/wombelix/.ansible/cp/062ff11488 -tt jailhost.example.com 'sudo -H -S -n  -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-gawnvpxcvrfxlqomuzwvrvzrulpackli ; jexec 68 /bin/sh -c '"'"'"'"'"'"'"'"'/bin/sh -c '"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'rm -f -r '"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'~ansible/.ansible/tmp/ansible-tmp-1648330350.7033346-13083-29065725208230/'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"' > /dev/null 2>&1'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"''"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<jailhost.example.com> (0, b'', b'Shared connection to jailhost.example.com closed.\r\n')
static@jailhost.example.com | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/local/bin/python3.8"
    },
    "changed": false,
    "module_stderr": "Shared connection to jailhost.example.com closed.\r\n",
    "module_stdout": "/usr/local/bin/python3.8: can't open file '\"'\"'\"'~ansible/.ansible/tmp/ansible-tmp-1648330350.7033346-13083-29065725208230/AnsiballZ_setup.py'\"'\"'\"': [Errno 2] No such file or directory\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 2
}
```

After applying https://github.com/austinhyde/ansible-sshjail/pull/36 everything seem to be ok, `ansible_facts` where returned from inside the jail as expected.
