### ISSUE TITLE
Temp execution files left behind

### ISSUE THREAD

**Issue by nkiraly** [austinhyde/ansible-sshjail#3]
When doing jail ansible operations, temp files are left behind on the jail host file system, such as 
/tmp/tmp.qVMkK8mt

Might be from this copy instead of move
https://github.com/austinhyde/ansible-sshjail/blob/643e2b3dbb08a0b7a887ab076529644113e582d5/sshjail.py#L49

e.g.
https://github.com/austinhyde/ansible-sshjail/blob/643e2b3dbb08a0b7a887ab076529644113e582d5/sshjail.py#L113

**Comment by austinhyde** [comment]
Should be fixed in 9e8c542
